export const CATALOG_REPOSITORY = Symbol('CATALOG_REPOSITORY');
export const CUSTOMER_REPOSITORY = Symbol('CUSTOMER_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const MARKETPLACE_CSV_READER = Symbol('MARKETPLACE_CSV_READER');
export const TEMPORARY_FILE_STORAGE = Symbol('TEMPORARY_FILE_STORAGE');
export const OUTPUT_STRATEGY = Symbol('OUTPUT_STRATEGY');
